### ISSUE TITLE
self.token_classification_task: TokenClassificationTask = token_classification_task_clazz()？

### ISSUE THREAD

**Issue by CaptionwWaterfall** [asappresearch/structshot#2]
I run the run_pl_ner.py and meet an error in： File "run_pl_ner.py", line 34

self.token_classification_task: TokenClassificationTask = token_classification_task_clazz()

SyntaxError: invalid syntax

How should I deal with it？

**Comment by yi-asapp** [comment]
Did you successfully set up the env?
I suggest using virtualenv

```
python3 -m venv venv
source venv/bin/activate
pip install -e .
```
